defmodule Scoreboard.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:teams, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :name, :text
      add :short_name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:skaters, primary_key: false) do
      add :team_id, references(:teams, column: :id, name: "skaters_team_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_active, :boolean
      add :legal_name, :text
      add :name, :text, null: false
      add :number, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:skaters, [:team_id, :number],
             name: "skaters_unique_number_per_team_index"
           )

    create table(:jams, primary_key: false) do
      add :game_id, references(:games, column: :id, name: "jams_game_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :away_lead, :boolean
      add :home_lead, :boolean
      add :away_points, :bigint
      add :home_points, :bigint
      add :period, :bigint
      add :jam_number, :bigint
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:games, primary_key: false) do
      add :state, :text, null: false
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :timeout_clock_running, :boolean
      add :lineup_clock_running, :boolean
      add :jam_clock_running, :boolean
      add :period_clock_running, :boolean
      add :timeout_caller, :text
      add :current_jam_number, :bigint, null: false
      add :current_period, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:game_teams, primary_key: false) do
      add :team_id, references(:teams, column: :id, name: "game_teams_team_id_fkey", type: :uuid),
        null: false

      add :game_id, references(:games, column: :id, name: "game_teams_game_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :official_reviews_remaining, :bigint
      add :timeouts_remaining, :bigint
      add :score, :bigint
      add :designation, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `game_teams` table without the `game_teams_game_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `game_teams` table without the `game_teams_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:game_teams)

    drop table(:games)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `jams` table without the `jams_game_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:jams)

    drop_if_exists unique_index(:skaters, [:team_id, :number],
                     name: "skaters_unique_number_per_team_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `skaters` table without the `skaters_team_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:skaters)

    drop table(:teams)
  end
end
