defmodule Scoreboard.Repo.Migrations.CreateGameEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:game_events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :version, :bigint, null: false
      add :state, :map, null: false
      add :payload, :map, null: false, default: %{}
      add :action, :text, null: false
      add :sequence, :bigint, null: false
      add :game_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:game_events, [:game_id, :sequence],
             name: "game_events_game_sequence_index"
           )
  end

  def down do
    drop_if_exists unique_index(:game_events, [:game_id, :sequence],
                     name: "game_events_game_sequence_index"
                   )

    drop table(:game_events)
  end
end